export const apiConfig = {
  baseUrl: process.env.NEXT_PUBLIC_API_BASE_URL || "https://api.horses.market/api",
  serverUrl: process.env.NEXT_PUBLIC_SERVER_URL || "https://api.horses.market",
  imageBaseUrl: process.env.NEXT_PUBLIC_IMAGE_BASE_URL || "https://api.horses.market/img",
  timeout: 20000,
  endpoints: {
    auth: {
      login: "/Auth/Login",
      logout: "/Auth/Logout",
      refreshToken: "/Auth/RefreshToken",
      forgotPassword: "/Auth/ForgotPassword",
      verifyOtp: "/Auth/VerifyOtp",
      resendOtp: "/Auth/ResendOtp",
      resetPassword: "/Auth/ResetPassword",
      verificationData: "/Auth/GetMyVerificationData",
      deleteAccount: "/Auth/DeleteMyAccount",
    },
    auctions: {
      list: "/Auctions/GetAuctions",
      myAuctions: "/Auctions/GetMyAuctions",
      details: (id: string) => `/Auctions/GetById?id=${id}`,
      create: "/Auctions/Create",
      stop: "/Auctions/StopAuction",
      accept: "/Auctions/AcceptAuction",
      delete: "/Auctions/Delete",
    },
    listings: {
      list: "/Products/GetProducts",
      sellers: "/Users/GetStableOwners",
      categories: "/Categories/GetAll",
      details: (id: string) => `/Products/GetProductById?id=${id}`,
    },
    categories: {
      list: "/Categories/GetAll",
      details: "/Categories/GetById",
      create: "/Categories/Create",
      update: "/Categories/Update",
      delete: "/Categories/Delete",
      openingClosing: "/Categories/GetCategoriesOpeningClosing",
    },
    breeds: {
      list: "/Breeds/GetAll",
      details: "/Breeds/GetById",
      create: "/Breeds/Create",
      update: "/Breeds/Update",
      delete: "/Breeds/Delete",
    },
    users: {
      list: "/Users/GetUsersByRole",
      dashboardStats: "/Users/DashboardStats",
      byRole: "/Users/GetUsersByRole",
      stableOwners: "/Users/GetStableOwners",
      storeOwners: "/Users/GetStoreOwners",
      stores: "/Users/GetStores",
      businessDetails: "/Users/GetBusinessProfileDetails",
      advertiserDetails: "/Users/GetAdvertiserDetails",
      customerDetails: "/Users/GetCustomerDetails",
      updateStatus: (id?: string) => id ? `/Users/UpdateUserStatus?userId=${id}` : "/Users/UpdateUserStatus",
      updateFeatures: "/Users/UpdateBusinessFeatures",
      updateBusinessProfile: "/Users/UpdateBusinessProfile",
      updateUserProfile: "/Users/UpdateUserProfile",
      verificationRequests: "/Users/GetVerificationRequests",
      approveVerification: "/Users/ApproveVerification",
      rejectVerification: "/Users/RejectVerification",
    },
    accounting: {
      dashboard: "/Admin/GetAccountingDashboard",
      privacyPolicy: "/Admin/GetPrivacyPolicy",
      termsAndConditions: "/Admin/GetTermsAndConditions",
      updateSysPage: "/Admin/UpdateSysPage",
    },
    payments: {
      list: "/Payments/GetAllPayments",
      details: "/Payments/GetPaymentById",
      status: "/Payments/GetPaymentStatus",
    },
    reviews: {
      list: "/Reviews/GetAllReviews",
      sellerReviews: "/Reviews/GetSellerReviews",
      average: "/Reviews/GetAverage",
      delete: "/Reviews/Delete",
    },
    complaints: {
      list: "/Complaints/GetAll",
      updateStatus: "/Complaints/UpdateStatus",
    },
    tickets: {
      liveReports: "/LiveRepots/GetRepotsLive",
    },
    ads: {
      list: "/Ads/GetAllAds",
      details: "/Ads/GetById",
      add: "/Ads/AddAd",
      changeStatus: "/Ads/ChangeStatus",
      delete: "/Ads/DeleteAd",
    },
    plans: {
      list: "/FeaturePlansManagement/GetPlans",
      create: "/FeaturePlansManagement/CreateFeaturePlan",
      update: "/FeaturePlansManagement/UpdateFeaturePlan",
      toggleStatus: "/FeaturePlansManagement/ToggleFeaturePlanStatus",
    },
    coupons: {
      list: "/Coupons/GetAll",
      create: "/Coupons/Create",
      update: "/Coupons/Update",
      changeStatus: "/Coupons/ChangeStatus",
      delete: "/Coupons/Delete",
      validate: "/Coupons/ValidateCoupon",
    },
    analytics: {
      overview: "/Users/DashboardStats",
    },
    notifications: {
      list: "/Notifications/Get",
      markAsRead: "/Notifications/MarkAsRead",
      // Note: GetUnreadCount, MarkAllAsRead, SendNotification, Delete do NOT exist in the API
    },
  },
  cookieNames: {
    auth: process.env.NEXT_PUBLIC_AUTH_COOKIE_NAME || "horses_admin_token",
    refresh: process.env.NEXT_PUBLIC_REFRESH_COOKIE_NAME || "horses_admin_refresh_token",
  },
};

