import { NavigationItem } from "@/types/common";

export const siteConfig = {
  name: "منصة الخيول والمواشي",
  nameEn: "Horses & Livestock Admin",
  description: "لوحة التحكم الإدارية لإدارة المزادات وبائعي المواشي والمستلزمات",
  defaultLocale: "ar",
  direction: "rtl",
  sidebarNav: [
    {
      id: "overview",
      title: "Dashboard",
      titleAr: "لوحة التحكم",
      href: "/",
      iconName: "Gauge",
    },
    {
      id: "livestock-sellers",
      title: "Livestock Sellers",
      titleAr: "إدارة بائعي المواشي",
      href: "/listings/sellers",
      iconName: "Users",
    },
    {
      id: "supplies-sellers",
      title: "Supplies Sellers",
      titleAr: "بائعي المستلزمات",
      href: "/listings/supplies-sellers",
      iconName: "UsersRound",
    },
    {
      id: "customers",
      title: "Customers Management",
      titleAr: "إدارة العملاء",
      href: "/users",
      iconName: "FileText",
    },
    {
      id: "categories",
      title: "Categories Management",
      titleAr: "إدارة التصنيفات",
      href: "/listings/categories",
      iconName: "LayoutGrid",
    },
    {
      id: "auctions",
      title: "Auctions Management",
      titleAr: "إدارة المزادات",
      href: "/auctions",
      iconName: "Gavel",
    },
    {
      id: "reports",
      title: "Reports & Analytics",
      titleAr: "التقارير والإحصائيات",
      href: "/orders",
      iconName: "FileSpreadsheet",
    },
    {
      id: "reviews",
      title: "Complaints & Reviews",
      titleAr: "الشكاوى والتقييمات",
      href: "/reviews",
      iconName: "HelpCircle",
    },
    {
      id: "user-accounts",
      title: "User Accounts",
      titleAr: "حسابات المستخدمين",
      href: "/accounts",
      iconName: "UserCheck",
    },
    {
      id: "tickets",
      title: "Reports & Tickets",
      titleAr: "البلاغات",
      href: "/tickets",
      iconName: "ShieldAlert",
    },
    {
      id: "ads",
      title: "Ads Management",
      titleAr: "الإعلانات",
      href: "/ads",
      iconName: "Megaphone",
    },
    {
      id: "accounting",
      title: "Accounting & Finance",
      titleAr: "المحاسبة",
      href: "/accounting",
      iconName: "Calculator",
    },
    {
      id: "invoices",
      title: "Invoices",
      titleAr: "الفواتير",
      href: "/invoices",
      iconName: "Receipt",
    },
    {
      id: "notifications",
      title: "Notifications",
      titleAr: "الإشعارات والتنبيهات",
      href: "/notifications",
      iconName: "Bell",
    },
    {
      id: "settings",
      title: "Settings",
      titleAr: "إعدادات",
      href: "/settings",
      iconName: "Settings",
    },
  ] as NavigationItem[],
};
